### ISSUE TITLE
Open to suggestions?

### ISSUE THREAD

**Issue by Steve-Mcl** [naimo84/awesome-nodered#7]
Hi, are you open to suggestions?

#### Perhaps a new category for image processing...
https://flows.nodered.org/node/node-red-contrib-image-tools (disclaimer: I am the author, however it is very popular lib for editing images, building and decoding 2D and 3D barcodes))
[image-output](https://github.com/rikukissa/node-red-contrib-image-output)  (move to this new section)

#### Additional entries under [node-red-dashboard](https://github.com/node-red/node-red-dashboard)...
&nbsp; &nbsp; * https://flows.nodered.org/node/node-red-contrib-ui-svg
&nbsp; &nbsp; * https://flows.nodered.org/node/node-red-contrib-ui-contextmenu

#### For the time section...
[cron-plus](https://flows.nodered.org/node/node-red-contrib-cron-plus) (disclaimer: I am the author, however it has high praise for its flexibility & capabilities & is very popular)

#### For the parsers section...
https://flows.nodered.org/node/node-red-contrib-buffer-parser (disclaimer: I am the author, however it is very powerful accompanying node for PLC/Modbus type data (and more))

**Comment by naimo84** [comment]
Hi @Steve-Mcl, 

Sorry it took a while, but I've added all your links to the list. 
Thanks for pointing it out 👍 

Greets,
Benjamin
